local_costmap:
  global_frame: $(arg tf_prefix_slashed)odom # Before there was odom_comb
  rolling_window: true
  raytrace_range: 6.0
  resolution: 0.05
  z_resolution: 0.15
  z_voxels: 8
  inflation:
    cost_scaling_factor: 10.0 
    inflation_radius:     0.6  
  width: 4.0
  height: 4.0
  origin_x: 0.0
  origin_y: 0.0
  
  plugins:
    - name: obstacles
      type: "costmap_2d::VoxelLayer"
    - name: inflation
      type: "costmap_2d::InflationLayer"
